services:
  litellm-proxy:
    image: ghcr.io/berriai/litellm:main-latest
    pull_policy: always
    ports:
      - "4000:4000"
    volumes:
      - ./litellm/config.yaml:/app/config.yaml
    command: --config /app/config.yaml --detailed_debug
    restart: always
    environment:
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_BASE=${AZURE_API_BASE}


  docling:
    image: quay.io/docling-project/docling-serve:latest  # API server
    # For CPU-only. If you have NVIDIA GPU, use :docling-serve-cu128 or cu126
    ports:
      - "5001:5001"
    environment:
      - DOCLING_SERVE_ENABLE_UI=1        # optional: web UI at /ui
      # Optional performance knobs (safe defaults if omitted):
      # - DOCLING_SERVE_NUM_WORKERS=2
      # - DOCLING_SERVE_MAX_REQUEST_SIZE=50
    restart: unless-stopped

  voyage-shim:
    build:
      context: ./voyage-shim
      dockerfile: Dockerfile
    environment:
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - VOYAGE_MODEL=${VOYAGE_MODEL}
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8081/rerank", "-X", "POST", "-H", "Content-Type: application/json", "-d", "{\"query\":\"ping\",\"documents\":[\"a\"],\"model\":\"rerank-2.5\"}"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:latest
    pull_policy: always
    ports:
      - "3020:8080"
    environment:
      - ENABLE_WEBSOCKET_SUPPORT=false
      - STORAGE_PROVIDER=${STORAGE_PROVIDER}  # This is crucial!
      - ENV=${ENV}
      - DATABASE_URL=${DATABASE_URL}
      - VECTOR_DB=${VECTOR_DB}
      # S3 Configuration
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION_NAME=${S3_REGION_NAME}  # Changed from S3_DEFAULT_REGION
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - DOCLING_SERVER_URL=http://docling:5001
    # volumes:
    #    - open-webui-data:/app/backend/data
      # - ./persistent-data:/app/backend/data
#      - /Users/cristhian.soria/Documents/dev/:/app/repos:ro
    depends_on:
      - litellm-proxy
      - docling
      - voyage-shim
    restart: always

volumes:
  open-webui-data: 
  persistent-data: