services:
  litellm-proxy:
    image: ghcr.io/berriai/litellm:main-latest
    pull_policy: always
    ports:
      - "4000:4000"
    volumes:
      - ./litellm/config.yaml:/app/config.yaml
    command: --config /app/config.yaml --detailed_debug
    restart: always
    environment:
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_BASE=${AZURE_API_BASE}

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:latest
    pull_policy: always
    ports:
      - "3020:8080"
    environment:
      - ENABLE_WEBSOCKET_SUPPORT=false
      - STORAGE_PROVIDER=${STORAGE_PROVIDER}  # This is crucial!
      - ENV=${ENV}
      - DATABASE_URL=${DATABASE_URL}
      # S3 Configuration
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION_NAME=${S3_REGION_NAME}  # Changed from S3_DEFAULT_REGION
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
    volumes:
      # - open-webui-data:/app/backend/data
      # - ./persistent-data:/app/backend/data
      - /Users/cristhian.soria/Documents/dev/:/app/repos:ro
    depends_on:
      - litellm-proxy
    restart: always

volumes:
  open-webui-data: 
  persistent-data: