litellm_settings:
  debug: true
  detailed_debug: true

model_list:
  - model_name: gpt-4.1
    litellm_params:
      model: azure/gpt-4.1
      api_key: ${AZURE_API_KEY}
      api_base: ${AZURE_API_BASE}
      api_version: 2025-01-01-preview

  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o-08-06
      api_key: ${AZURE_API_KEY}
      api_base: ${AZURE_API_BASE}
      api_version: 2025-01-01-preview

  - model_name: o3-mini
    litellm_params:
      model: azure/o3-mini
      api_key: ${AZURE_API_KEY}
      api_base: ${AZURE_API_BASE}
      api_version: 2025-01-01-preview
